### PR TITLE
Clarifications, Additions to README.md

### LINKED ISSUE #8: Provide more details in README
In the sections of the readme for creating new services/microservices, there should be more complete instructions on what message to send in the chat server, and perhaps an example.

A guide or link to getting on the chat server should also be added or linked here, as it is not immediately obvious, and simply clicking the `open-horizon-examples` link will not work if you are not already on the chat server, and this may just confuse new contributors instead.

### PR DESCRIPTION
**Pull request by aesop0**
Signed-off-by: Adam-Ayan [adam.ayan84@gmail.com](adam.ayan84@gmail.com)

## Issues 

Fixes #8 

Specified:
- Exactly how to join the Matrix group chat open-horizon-examples
- What kind of message to send to request a service
- An example of such message
- Indicated that it should tag Troy Fine by typing or selecting the indicated username of his. 

## Checklist 

- [x] The Guide has been linted against a language and grammar tool.
- [x] The Guide is easy to follow and understand for new users.

### CODE REVIEW

**Review by joewxboy — CHANGES_REQUESTED** [review]
Looks good to me, except you appear to also have a `f OA` file attached to the commit that should be removed.  Can you delete that file?

**Comment by aesop0** [comment]
(Here comes my attempt to satisfy the DCO check)

**Review by johnwalicki — CHANGES_REQUESTED** [review]
Agree with Joe - Can you delete this `fOA` file?

**Comment by aesop0** [comment]
After some struggling, I think I've done it, the unnecessary fOA file gone and DCO check passed!

**Review by johnwalicki — APPROVED** [review]

**Comment by johnwalicki** [comment]
Congratulations @Adam-Ayan  - you're now a Open Horizon contributor - Thanks!

**Pull request merged**
